plugins {
    id 'com.android.application'
}

android {
    namespace 'de.pierre.ebesuchermonitor'
    compileSdk 35

    defaultConfig {
        applicationId 'de.pierre.ebesuchermonitor'
        minSdk 21
        targetSdk 35
        versionCode 5
        versionName '0.1.4'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
